# -*- coding: utf-8 -*-
"""Untitled36.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gl-TFrxlp3cphHTpfiW5MlXQFfMNBZu9
"""

from eth_keys import keys
from eth_utils import to_checksum_address

# Custom private key (replace with your own 32-byte hex key)
private_key_hex = "2".zfill(64)

# Convert the private key from hex to bytes
private_key_bytes = bytes.fromhex(private_key_hex)

# Generate the private key object
private_key = keys.PrivateKey(private_key_bytes)

# Get the corresponding public key
public_key = private_key.public_key

# Generate the Ethereum address
eth_address = public_key.to_address()

# Convert to checksum address for better readability
checksum_address = to_checksum_address(eth_address)

# Print results
print(f"Private Key: {private_key}")
print(f"Public Key: {public_key}")
print(f"Ethereum Address: {checksum_address}")

